sudo: required
services:
  - docker

  before_install:
    - docker build -t bobbysoar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bobbysoar/react-test npm test -- --coverage

after_success:
  - docker build -t bobbysoar/multi-client ./client
  - docker build -t bobbysoar/multi-nginx ./nginx
  - docker build -t bobbysoar/multi-server ./server
  - docker build -t bobbysoar/multi-worker ./worker
# Log in to the docker cli (eventually aws ecs)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
# Tale the images and push them to docker hub (then aws ecs)
  - docker push bobbysoar/multi-client
  - docker push bobbysoar/multi-nginx
  - docker push bobbysoar/multi-server
  - docker push bobbysoar/multi-worker